_base_: 'configs/Base.yaml'
data:
  train:
    annotation_files:
      - dataset/annotations/totaltext_train.json
    img_rootdir:
      - dataset/totaltext/totaltext_train
    data_proportion:
      - 1
    augmentation:
      ResizeMinsizes:
        - 640
        - 672
        - 704
        - 736
        - 768
        - 800
        - 832
        - 864
        - 896
      ResizeMaxsize: 1280
  test:
    input_min_side: 896
    annotation_files: dataset/annotations/totaltext_test.json
    img_rootdir: dataset/totaltext/totaltext_test
    batch_size: 1

trainer:
  niter: 80000
  learning_rate: 1e-4
  batch_size: 4
  num_workers: 4
  optim: sgd
  lr_policy: poly
  save_dir: outputs/totaltext_finetune

inference:
  vis: True
  output_json_path: inference/totaltext_test.json
  output_vis_dir: inference/totaltext_test_vis
  