max_text_length: 25
false_label_num: 16
vocabulary_file: data/vocabulary/eng_vocabulary.txt
model:
  backbone: resnet50
  use_stride: 8
  with_deformable_encoder: True
  transformer_width: 512
  transformer_layers: 12
  transformer_heads: 8
  embed_dim: 512
  deformable_layer: 6

trainer:
  start_iter: 0
  niter: 200000
  log_freq: 50
  save_freq: 10000
  learning_rate: 1e-3
  batch_size: 16
  num_workers: 16
  optim: sgd
  momentum: 0.9
  weight_decay: 1e-5
  lr_policy: poly
  save_dir: outputs/pretrain

data:
  alphabet: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz !"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~
  ignore_case: True # TODO: Make sure?
  vocab_size: 70
  train:
    annotation_files:
      - data/annotations/synth800k.json
    img_rootdir:
      - /data/wujingjing/data_copy/SynthText
    data_proportion:
      - 1
    augmentation:
      RotateProb: 1
      RotateAngle: 10
      ResizeMinsizes:
        - 640
      ResizeMaxsize: 640
      BlurProb: 0.1
      ColorJitterProb: 0.5
  test:
    input_min_side: -1
    input_max_side: -1
    annotation_files: /path/to/annotation.txt
    batch_size: 1
    max_test_num: 5000

inference:
  thresh: 0.015
  vis: False
  output_json_path: path/to/output.json
  output_vis_dir: path/to/output_vis_dir
